---
- name: install munin-node
  apt: name={{ item }} state=present
  # update_cache=yes
  with_items:
      - munin-node
  when: ansible_os_family  == "Debian"

- name: install munin-node
  yum: name={{ item }} state=present
  # update_cache=yes
  with_items:
      - munin-node
  when: ansible_os_family  == "RedHat"

- name: define server ip address if it is not set
  set_fact:
      # munin_server_address: "{{ munin_group_search_prefix + '-munin-server'}}"
      munin_server_address: "{{ hostvars[groups[munin_group_search_prefix + '-munin-server'][0]]['ansible_' + munin__server_interface]['ipv4']['address']}}"
  when: munin_server_address is not defined

- name: define extra addresses if they are not set
  set_fact:
      munin_extra_allowed_address: []
  when: munin_extra_allowed_address is not defined

- name: create /var/log/munin
  file: state=directory dest=/var/log/munin
  
- name: munin.conf
  template:
      src=munin-node.conf
      dest=/etc/munin/munin-node.conf
      backup=yes
  register: munin_node
  notify: reload munin

- name: set munin_client_configuration_changed to yes
  set_fact:
      munin_client_configuration_changed: yes
  when: munin_node.changed
